# Generated by Django 5.0.1 on 2024-01-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_education_field_of_study"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="is_current",
            field=models.BooleanField(
                default=False, verbose_name="Currently working here"
            ),
        ),
        migrations.AddField(
            model_name="leadership",
            name="is_current",
            field=models.BooleanField(
                default=False, verbose_name="Currently working here"
            ),
        ),
    ]
