# Generated by Django 5.0.1 on 2024-01-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_experience_is_current_leadership_is_current"),
    ]

    operations = [
        migrations.AddField(
            model_name="skills",
            name="category",
            field=models.CharField(default="Select Category", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="education",
            name="related_courses",
            field=models.CharField(max_length=1000),
        ),
    ]
